<?xml version="1.0" encoding="UTF-8"?>
<testsuites errors="0" failures="1" skipped="0" tests="1" time="0.004074" timestamp="2015-02-11T10:50:48-07:00">
  <testsuite name="Successful Response" tests="1" errors="0" failures="1" skipped="0">
    <properties/>
    <testcase name="Solr Basics Successful Response Given I search for &quot;sea ice&quot; -&gt; Then I should get a valid response with results" time="0.003657">
      <failure message="failed Solr Basics Successful Response Given I search for &quot;sea ice&quot; -&gt; Then I should get a valid response with results" type="failed">
        <![CDATA[Connection refused - connect(2)
["./spec/acceptance/page_objects/solr_search_page.rb:13:in `query'", "spec/acceptance/steps/solr_steps.rb:16:in `block in <module:SolrSteps>'", "./spec/acceptance/solr.feature:6:in `run_step'", "./spec/acceptance/solr.feature:7:in `block (6 levels) in run'", "./spec/acceptance/solr.feature:6:in `each'", "./spec/acceptance/solr.feature:6:in `block (5 levels) in run'", "./spec/acceptance/solr.feature:6:in `I search for \"sea ice\"'"]]]>
      </failure>
    </testcase>
  </testsuite>
</testsuites>
